### PR TITLE
64-bit long mode support

### PR DESCRIPTION
**Pull request by jdadonut**
This changes the support from 16-bit to 64-bit long mode.

Requirements:
- Assembly is out of season, use zig to interact with the system.
- to build, run `zig build` and then run your equivalent of scripts/build.bat, and then run it using the vm of your choice. QEMU might work, but [Virtualbox w/ EFI support](https://wiki.osdev.org/UEFI#Downloading_UEFI_images) is preferred

### CODE REVIEW

**Comment by jdadonut** [comment]
checks will fail, i havent made a git actions check for this.

**Comment by mugman174** [comment]
ok imma test this myself

**Comment by mugman174** [comment]
I mean it's supposed to be assembler...

**Comment by jdadonut** [comment]
assembly runs on bios, zig compiled to efi code runs on uefi and automatically puts you in 64 bit long mode

**Comment by mugman174** [comment]
It doesn't work on GitHub Actions (see build 100). Am I supposed to do `zig build src/build.zig` or whatever?

**Pull request merged**
